# Sync repo to the Codeberg mirror
name: Repo sync GitHub -> Codeberg
on:
  push:
    branches:
    - '**'

jobs:
  codeberg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: yesolutions/mirror-action@v0.7.0
        with:
          REMOTE: "https://codeberg.org/swin-waterways/datasets.git"
          GIT_USERNAME: candrew
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
